
logger:
  # https://pytorch-lightning.readthedocs.io/en/stable/extensions/generated/pytorch_lightning.loggers.WandbLogger.html
  _target_: pytorch_lightning.loggers.WandbLogger
  project: brdf-capture
  name: ${experiment_name}

trainer:
  accelerator: gpu #cpu or gpu
  devices: auto
  num_nodes: 1
  max_epochs: 40
  max_steps: 20000
  check_val_every_n_epoch: 50

# https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelCheckpoint.html
checkpoint_monitor:
  save_top_k: 1
  every_n_epochs: 10
  filename: "{epoch}"
  dirpath: ${exp_output_root_path}/training


optimizer:
  name: Adam # SGD or Adam
  weight_decay: 0.0
  lr: 0.004
  warmup_steps_ratio: 0.0

lr_decay: # for Adam
  decay_start_epoch: 100