data:
  num_workers: 8
  batch_num: 1024
  batch_size: 8192
  dataset_name: sphere
  dataset_path: None
  shape:
    type: sphere
    center:
    - 0.0
    - 0.0
    - 0.0
    radius: 0.2
  pixel: true
  ray_diff: true
  custom_c2w: true
renderer:
  type: path_tracing_envmap_emitter
  brdf_sampling: true
  emitter_sampling: true
  indir_depth: 0
  camera:
    distance: 2.0
    number_of_views: 32
    look_at:
    - 0.0
    - 0.0
    - 0.0
    up:
    - 0.0
    - 1.0
    - 0.0
    camera_angle_x: 0.5
  emitter:
    type: envmap
    envmap_path: ./envmap.exr
  spp:
    train: 2048
    val: 2048
    test: 2048
  SPP_chunk: 16
  resolution:
  - 1024
  - 1024
material:
  type: MLPPBRBRDF
  hidden_layers:
  - 64
  - 128
  - 64
  - 32
  - 16
  activation: relu
  input_channels: 9
  output_channels: 1
model:
  ckpt_path: /localhome/zla247/theia2_data/output/BRDF-Fipt/Over-fit_experiments_2/sphere/Different_color_debug/training/model_0.20_0.20/last.ckpt
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: brdf-capture
    name: Different_color_debug
  trainer:
    accelerator: gpu
    devices: auto
    num_nodes: 1
    max_epochs: 5
    max_steps: 20000
    check_val_every_n_epoch: 5
  checkpoint_monitor:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 2
    every_n_epochs: 1
    filename: '{epoch}'
    dirpath: /localhome/zla247/theia2_data/output/BRDF-Fipt/Over-fit_experiments_2/sphere/Different_color_debug/training
  optimizer:
    name: Adam
    weight_decay: 0.0
    lr: 0.004
    warmup_steps_ratio: 0.0
  lr_decay:
    decay_start_epoch: 6
  parameter_num: 1
  roughness_range:
  - 0.2
  - 0.8
  metallic_range:
  - 0.2
  - 0.8
experiment_name: Different_color_debug
output_folder: /localhome/zla247/theia2_data/output/BRDF-Fipt/Over-fit_experiments_2
exp_output_root_path: /localhome/zla247/theia2_data/output/BRDF-Fipt/Over-fit_experiments_2/sphere/Different_color_debug
gt_folder: /localhome/zla247/theia2_data/output/BRDF-Fipt/Over-fit_experiments_2/sphere/Different_color_debug/roughness_0.20_metallic_0.20
global_train_seed: 42
