type: "path_tracing_envmap_emitter"
brdf_sampling: True
emitter_sampling: True
indir_depth: 0

camera:
  position: [0.0, 0.0, -2.0]
  look_at: [0.0, 0.0, 1.0]
  up: [0.0, 1.0, 0.0]
  camera_angle_x: 0.5

emitter:
  type: "envmap"
  envmap_path: "./envmap.exr"

spp:
  train: 64 
  val: 1024
  test: 64
SPP_chunk: 16

resolution: [1024, 1024]
