type: "path_tracing_fix_emitter"
brdf_sampling: True
emitter_sampling: True
indir_depth: 0

camera:
  distance: 2.0
  number_of_views: 1
  look_at: [0.0, 0.0, 0.0]
  up: [0.0, 1.0, 0.0]
  camera_angle_x: 0.5

emitter:
  type: "point"
  position: [-2.0, 2.0, 0.0]
  intensity: [50.0, 50.0, 50.0]
  radius: 0.1

spp:
  train: 256
  val: 1024
  test: 1024
SPP_chunk: 16

resolution: [1024, 1024]
