type: "LatentModel"
latent_dim: 64
hidden_layers: [128, 128, 64, 32, 16]
# hidden_layers: [128, 128, 128, 128, 128, 64, 32, 1]
# hidden_layers: [48, 48, 24, 12, 6]
# hidden_layers: [18, 36, 72, 36, 18, 9]
# hidden_layers: [18, 36, 72, 72, 36, 18, 9]
# hidden_layers: [100, 200, 100, 50, 25]c

activation: "relu"
input_channels: 9
output_channels: 1

