type: "LatentTexturedModel"
latent_dim: 16
use_gt_normal: False
predict_normal: True
colorful_texture: True
leaky_relu: True
texture_resolution: 2048
hidden_layers: [128, 128, 64, 32, 16]
# hidden_layers: [256, 256, 128, 64, 32, 16]
Gaussian_blur: False
activation: "relu"
input_channels: 9
prefilter: True

# Spherical Harmonics Encoding Options:
# use_nerfstudio_sh: False  # Set to True to use nerfstudio's SHEncoding instead of custom implementation
                             # Both implementations produce the same number of bases for degree=3: (degree+1)^2 = 16

# config 1:
larger_latent_dim: True
different_decoder: True
output_channels: 1

# # config 2:
# larger_latent_dim: True
# different_decoder: False
# output_channels: 1

# # config 3:
# larger_latent_dim: False
# different_decoder: False
# output_channels: 3
