type: "LatentTexturedModel"
latent_dim: 64
texture_resolution: 512
hidden_layers: [128, 128, 64, 32, 16]
# hidden_layers: [256, 256, 128, 64, 32, 16]
Gaussian_blur: True
activation: "relu"
input_channels: 9
output_channels: 1

