type: "SvPBRBRDF"

roughness: 0.2
metallic: 0.2
albedo: [1.0, 1.0, 1.0]
perlin_scale: 0.1
perlin_randomness: 0.1
normal_map: True # whether use normal map or sphere normals
scale_factor: 0.2 # scale factor for pbr maps

pbr_texture_path: '/localhome/zla247/theia2_data/theia2_data/BRDF-Fipt/fabric_pattern_07_4k/textures'