defaults:
  - data: sphere
  - renderer: dynamicpoint_emitter
  - model: direct
  - material: svlatent_model

experiment_name: test
dataset_folder: /mnt/data/colin/colin/BRDF-Fipt/reference_images
output_folder: /mnt/data/colin/colin/output/BRDF-Fipt/Over-fit_experiments_2
exp_output_root_path: ${output_folder}/${data.dataset_name}/${experiment_name}
gt_folder: ${dataset_folder}
metadata_path: ${gt_folder}
test_on_train: False
global_train_seed: 42
