defaults:
  - data: sphere
  - renderer: point_emitter
  - material: mlp_pbr
  - model: direct

experiment_name: Point-Emitter-Larger-MLP-Brdf-sampling_Non-Optimized-PBR-PROXY_run_1
output_folder: ./Over-fit_experiments
exp_output_root_path: ${output_folder}/${data.dataset_name}/${experiment_name}

global_train_seed: 42
